version: 2

registries:
  google-artifact-registry:
    type: docker-registry
    url: https://europe-west1-docker.pkg.dev
    username: _json_key_base64
    password: ${{ secrets.GOOGLE_ARTIFACT_REGISTRY_READ_TOKEN }}

updates:
  - package-ecosystem: docker
    directory: "/"
    registries:
      - google-artifact-registry
    schedule:
      interval: daily
